### ISSUE TITLE
dndzone: the inputbox is draggable and will cause the dropdown break

### ISSUE THREAD

**Issue by stevenyh3** [mskocik/svelecte#165] opened 2023-04-19 03:01 UTC
![image](https://user-images.githubusercontent.com/89871868/232955395-f4359dff-0102-4705-a8b5-19b3c10abb63.png)
![image](https://user-images.githubusercontent.com/89871868/232955486-2fa55261-5fbf-4ced-877c-14b3ddebe982.png)
As you can see, the input box is draggable and will cause the multiselection break.
Also, is it possible to passing in a custom event to check when finish dragging & drop the element in the dndzone? Such as on:drop, on: on:finalize.
Tks a lot!

**Comment by stevenyh3** [comment] 2023-04-20 19:35
Also can the outline style when dragging elements being removed?
The demo [here ](https://svelte.dev/repl/da2de4b9ed13465d892b678eba07ed99?version=3.44.0) can see that when dragging the elements, the style of dragging elements will be changed.

**Comment by firtrfl** [comment] 2024-01-24 15:38
![image](https://github.com/mskocik/svelecte/assets/110921282/e38c0fec-751d-4701-a172-c2f208e32e43)

Hi @mskocik and thanks for this amazing library. I have observed another bug. I am not exactly sure if it is the same as the one described above. But the problem is, that the "placeholder" text can be also dragged, but if that happens there is an error an you need to reload the window to be able to drag again the items.

I have fixed this locally by a small hack in `src/components/Control.svelte` where I set `dragDisabled: true` if the length of the `selectedOptions` is less than 1:

```svelte
  // prevent dragging if there are no selected items
  // to solve the bug when trying to drag an empty selection
  $: dragDisabled = selectedOptions.length < 1;
</script>

<div
  class="sv-control"
  class:is-active={$hasFocus}
  class:is-disabled={disabled}
  on:mousedown|preventDefault
  on:click|preventDefault={focusControl}
>
  <slot name="icon" />
  <!-- selection & input -->
  <div
    class="sv-content sv-input-row"
    class:has-multiSelection={multiple}
    use:dndzone={{
      items: selectedOptions,
      flipDurationMs,
      type: inputId,
      dragDisabled: dragDisabled,
    }}
    on:consider
    on:finalize
  >
```

This is probably not the best way of doing it but I just thought I would share.

**Comment by mskocik** [comment] 2024-02-16 19:11
This is issue in `svelte-dnd-action`. Related issue https://github.com/isaacHagoel/svelte-dnd-action/issues/452.

However in current `master` and therefore in upcoming v4 it will be fixed.

**Closed as completed by mskocik** 2024-02-16 19:11 UTC
Labels: bug, feature request
